<?php
$titles["wform_74"]=
		array(
			"title" => "test",
			"db"=>"wform_74",
			"uid"=>"tbw74",
			"date"=>"entry_date",
			"did"=>"id",
			"defered"=>array(),
			"abbr"=>"WF74",
			"plurals"=>array('wform_sub_1'=>array(
			'table'=>'wf_74_sub_1',
			'index'=>'wf_id',
			'fields'=>array("fld_0","fld_1"),
			'eparser'=>false
				)),
			"referral"=>"",
			"next_visit"=>"",
			"form_type"=>"contus"
		);
?>