<?php
### Copyright (c) 2004, The dotProject Development Team dotproject.net and sf.net/projects/dotproject ###
### All rights reserved. Released under GPL License. For further Information see LICENSE ###

### CONFIGURATION FILE AUTOMATICALLY GENERATED BY THE DOTPROJECT INSTALLER ###
### FOR INFORMATION ON MANUAL CONFIGURATION AND FOR DOCUMENTATION SEE ./includes/config-dist.php ###

$dPconfig['dbtype'] = 'mysql';
$dPconfig['dbhost'] = 'localhost';
$dPconfig['dbname'] =  'simast';
// $dPconfig['dbname'] =  'crowdl5_simast';
//$dPconfig['dbname'] =  'leaadmin_kario';
// 'kib-now';'rtt2';
//
//'kib-now';
// 'db11-kan';///'kangemi-test'; ///'testkario';//'mukdan';//'kawangware';//'kariobangi';////'mukuru';//'kibera';//'dandora';/////////////////'leatoto'
$dPconfig['dbuser'] = 'crowdl5_simast';
$dPconfig['dbpass'] = 'SImast123';
$dPconfig['dbuser'] = 'root';
$dPconfig['dbpass'] = '';
$dPconfig['dbuser'] = 'simastadmin';
$dPconfig['dbpass'] = 'fasil';
$dPconfig['dbpersist'] = false;
$dPconfig['root_dir'] = $baseDir;
$dPconfig['base_url'] = $baseUrl;
$dPconfig['zip_path'] = "zip";
$GMapKey='AIzaSyAlYQSeRlVg78rUh0mUUZRO4BI0x8aKhqM';
